language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - LARAVEL=5.1
  - LARAVEL=5.2
  - LARAVEL=dev-master

matrix:
  allow_failures:
    - env: LARAVEL=dev-master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require "illuminate/support" "$LARAVEL.*"
  - php composer.phar install --dev

script: phpunit

notifications:
  email: false
